---
- name: Configure auditd rules
  hosts: vms
  vars_files:
    - secret
  become: yes
  tasks:
    - name: Ensure auditd installed
      when: ansible_os_family != "Debian"
      package:
        name: audit
        state: present

    - name: Ensure auditd installed on Debian
      apt:
        name: auditd
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Deploy auditd rules
      copy:
        src: ../Scripts/auditd-rules
        dest: /etc/audit/rules.d/standard.rules
        owner: root
        group: root
        mode: '0600'
      notify: Restart auditd

  handlers:
    - name: Restart auditd
      service:
        name: auditd
        state: restarted
        use: service
