[vms]
192.168.122.204 ansible_user=hna ansible_become_password='aoeu'
192.168.122.236 ansible_ssh_private_key_file=/home/hna/.ssh/vms ansible_user=hna ansible_become_password='aoeu'
192.168.122.159 ansible_ssh_private_key_file=/home/hna/.ssh/vms ansible_user=hna ansible_become_password='aoeu'
192.168.122.241 ansible_ssh_private_key_file=/home/hna/.ssh/comp-ansible ansible_user=hna ansible_become_password='asdf'
192.168.122.118 ansible_ssh_private_key_file=/home/hna/.ssh/comp-ansible ansible_user=hna ansible_become_password='asdf'
