---
- name: Deploy iptables script
  hosts: vms
  vars_files:
    - secret
  become: yes
  tasks:
    - name: Ensure iptables is installed
      package:
        name: iptables
        state: present

    - name: Copy over script
      copy:
        src: ../Scripts/autofirewall.sh
        dest: /tmp/save
        mode: '0755'

    - name: Excute script
      become: yes
      args:
        chdir: /tmp
      shell: /tmp/save
      async: 3000000
      poll: 0
