---
- name: Update systems
  hosts: vms
  vars_files:
    - secret
  become: yes
  become: true
  gather_facts: true

  tasks:
    # --- DEBIAN / UBUNTU ---
    - name: Update Debian-based systems
      when: ansible_os_family == "Debian"
      block:
        - name: Update apt cache and upgrade packages
          ansible.builtin.apt:
            update_cache: yes
            upgrade: dist
            autoremove: yes

    # --- RHEL / CENTOS / ROCKY / ALMA ---
    - name: Update RHEL-based systems
      when: ansible_os_family == "RedHat"
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: yes

    # --- SUSE / SLES ---
    - name: Update SUSE-based systems
      when: ansible_os_family == "Suse"
      community.general.zypper:
        name: "*"
        state: dist-upgrade
        update_cache: yes

    # --- ALPINE ---
    - name: Update Alpine-based systems
      when: ansible_os_family == "Alpine"
      community.general.apk:
        name: "*"
        state: latest
        update_cache: yes
